version: "3.6"
services:
  web:
    build: .
    depends_on: 
      - redis
    ports:
      - 8000:8000
    environment:
      - ENVIRONMENT=PROD
      - HOST=localhost
      - PORT=8000
      - REDIS_HOST=localhost
      - REDIS_PORT=6379
      - REDIS_DB=0
  redis:
    image: redis:5.0
    ports:
    - "6379:6379"
